version: '3.5'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4576:4576"
      - "8080:8080"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-2
      - DEBUG=1
    networks:
      - ed-match-data-crawling-module-network

  localstack.config:
    container_name: localstack-config
    build:
      context: ./docker-setup/localstack-config
    environment:
      - AWS_SECRET_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - REGION_NAME=eu-west-2
      - ENDPOINT_URL=localstack
    depends_on:
      - localstack
    networks:
      - ed-match-data-crawling-module-network

networks:
    ed-match-data-crawling-module-network: 
        name: flow-network