AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Templates the infrastructure of the ed-match-data-crawling-module.
  Consists of a crawler function that scrapes a specific URL and a function, Insertor, that persists the data.
  Crawl jobs are scheduled and enqueued by an AWS EventBridge rule that triggers nightly.
  An ed-match-data-notifications queue is exposed to let consumers outside the module know of successful data inserts.

Globals:
  Function:
    MemorySize: 256
    Environment:
      Variables:
        INSERTOR_INGEST_QUEUE_URL: !Ref InsertorIngestQueue

Resources:

  Insertor:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 180
      CodeUri: ./lambda/ed-match-data-insertor/
      Handler: function.lambda_handler
      Policies:
        - AWSLambdaExecute
        - AmazonSQSFullAccess #  Todo: replace with execution role
      VpcConfig: #  Todo: move to parameters
        SecurityGroupIds:
          - sg-65ca6405
        SubnetIds:
          - subnet-dca67590
          - subnet-ddc283b4
          - subnet-547bf62e
      Events:
        IngestJobTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt InsertorIngestQueue.Arn
            BatchSize: 1
            Enabled: true
      Environment:
        Variables:
          MATCH_DATA_NOTIFICATIONS_QUEUE_URL: !Ref MatchDataNotificationsQueue
          MYSQL_CONNECTION_STRING: 'overwrite_this'
      Tags:
        project: ed-sports-betting

  CrawlerXXC:
    Type: AWS::Serverless::Function  
    Properties:
      Runtime: python3.7
      Timeout: 180
      CodeUri: ./lambda/ed-match-data-xxc-crawler/
      Handler: function.lambda_handler
      Policies:
        - AWSLambdaExecute
        - AmazonSQSFullAccess #  Todo: replace with execution role
      Events:
        CrawlerXCCJobTrigger:
          Type: SQS 
          Properties:
            Queue: !GetAtt CrawlerXXCJobs.Arn
            BatchSize: 1
            Enabled: true
      Environment:
        Variables:
          BASE_CRAWL_URL: 'overwrite_this'
          JOB_QUEUE_URL: !Ref CrawlerXXCJobs
      Tags:
        project: ed-sports-betting

  CrawlJobScheduler:
    Type: AWS::Events::Rule
    Properties: 
      Description: Issue a crawl job nightly at 11pm
      ScheduleExpression: "cron(0 23 * * ? *)"
      RoleArn: !GetAtt CrawlJobSchedulerRole.Arn
      State: ENABLED
      Targets:
        - Arn: !GetAtt CrawlerXXCJobs.Arn
          Id: ed-match-data-crawling-module-xxc-crawler-jobs
          InputTransformer:
            InputPathsMap: 
              date_today : $.time
            InputTemplate: '{"starting_date": <date_today>, "division": "premier-league"}'

  CrawlerXXCJobs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ed-match-data-crawling-module-xxc-crawler-jobs
      VisibilityTimeout: 240
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CrawlerJobsGutterQueue.Arn
        maxReceiveCount: 1  # Prevent CrawlerXXC from receiving the same message again

  CrawlerJobsGutterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ed-match-data-crawling-module-crawler-jobs-dlq
      MessageRetentionPeriod: 86400  # Purge messages from the gutter after a day

  InsertorIngestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ed-match-data-crawling-module-ingest.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      MessageRetentionPeriod: 1209600

  MatchDataNotificationsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ed-match-data-notifications
      MessageRetentionPeriod: 1209600

  CrawlJobSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: queue-crawl-job-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow #  Todo: reduce the policy's scope
                Action: '*'
                Resource: '*'

# Useful links
# Implicitly generated resources: https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#s3
# Event source types: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#event-source-types
# Resource types: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction