AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Defines the infrastructure of the whole ed-match-data-crawling-module as code.
  The CrawlerXXC function receives jobs via the CrawlerXXCJobs queue.
  MatchDataIngestQueue receives the match data batches.

Globals:
  Function:
    MemorySize: 512
    Environment:
      Variables:
        BASE_CRAWL_URL: 'override_connection_string'
        MATCH_DATA_INGEST_QUEUE_URL: !Ref MatchDataIngestQueue

Resources:  # Implicitly generated resources https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#s3

  DailyCrawlJob:
    Type: AWS::Events::Rule
    Properties: 
      Description: Issue a crawl job at the end of every day
      ScheduleExpression: "cron(0 23 * * ? *)"
      RoleArn: !GetAtt DailyCrawlJobRole.Arn
      State: ENABLED
      Targets:
        - Arn: !GetAtt CrawlerXXCJobs.Arn
          Id: ed-match-data-crawling-module-xxc-crawler-jobs
          InputTransformer:
            InputPathsMap: 
              date_today : $.time
            InputTemplate: '{"starting_date": <date_today>, "division": "premier-league"}'

  DailyCrawlJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: queue-crawl-job-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  CrawlerXXCJobs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ed-match-data-crawling-module-xxc-crawler-jobs
      VisibilityTimeout: 240
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CrawlerJobsGutterQueue.Arn
        maxReceiveCount: 1  # Prevent CrawlerXXC from receiving the same message again

  CrawlerJobsGutterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ed-match-data-crawling-module-crawler-jobs-dlq
      MessageRetentionPeriod: 86400  # Purge messages from the gutter after a day

  CrawlerXXC:
    Type: AWS::Serverless::Function  # Creates a Lambda function, role and event source mappings https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Runtime: python3.7
      Timeout: 180
      CodeUri: ./lambda/ed-match-data-xxc-crawler/
      Handler: crawler_function.lambda_handler
      Policies:
        - AWSLambdaExecute # Managed Policy
        - AmazonSQSFullAccess # Managed Policy
      Events:
        CrawlerXCCJobTrigger:
          Type: SQS # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#event-source-types
          Properties:
            Queue: !GetAtt CrawlerXXCJobs.Arn
            BatchSize: 1
            Enabled: true
      Environment:
        Variables:
          JOB_QUEUE_URL: !Ref CrawlerXXCJobs
      Tags:
        project: ed-sports-betting

  MatchDataIngestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ed-match-data-crawling-module-ingest.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      MessageRetentionPeriod: 1209600  # Purge messages from the gutter after a day

  Insertor:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 180
      CodeUri: ./lambda/ed-match-data-insertor/
      Handler: crawler_function.lambda_handler
      Policies:
        - AWSLambdaExecute # Managed Policy
        - AmazonSQSFullAccess # Managed Policy
      Events:
        IngestJobTrigger:
          Type: SQS # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#event-source-types
          Properties:
            Queue: !GetAtt MatchDataIngestQueue.Arn
            BatchSize: 1
            Enabled: true
      Environment:
        Variables:
          JOB_QUEUE_URL: !Ref CrawlerXXCJobs
      Tags:
        project: ed-sports-betting